[TASK] Move php-cs-fixer to build dir
TYPO3BestPractices/tea pull request #1353
Opened 2024-07-02 22:32 UTC by lukaszuznanski

Part of: #1186

2024-07-03 07:03 UTC, oliverklee requested changes
We also need to update the `.gitattributes` to no longer exclude the file anymore (as we already exclude `Build/`).

2024-07-03 07:03 UTC, oliverklee commented on composer.json
> +			"rm Build/php-cs-fixer/.php-cs-fixer.php",
Please let's keep this list sorted. Also, I suggest we do a `rm -rf Build` instead.

2024-07-07 22:01 UTC, lukaszuznanski commented
> We also need to update the `.gitattributes` to no longer exclude the file anymore (as we already exclude `Build/`).

Done. I also removed tests build directory from excludes, as its located in `Build` also.

2024-07-08 07:39 UTC, oliverklee requested changes

2024-07-08 07:39 UTC, oliverklee commented on composer.json
> +		"ci:php:cs-fixer": "php-cs-fixer fix --config ./Build/php-cs-fixer/.php-cs-fixer.php -v --dry-run --diff",
Looks generally very good. I think we can also change from a hidden file to a non-hidden-file, though, to make the live of developers a bit easier.

```suggestion
		"ci:php:cs-fixer": "php-cs-fixer fix --config ./Build/php-cs-fixer/php-cs-fixer.php -v --dry-run --diff",
```

(We'll then also need the same change in line 175, and we need to rename the config file.)

2024-07-08 07:42 UTC, oliverklee requested changes
We also need to adapt the `prepare-release` Composer script.

2024-09-17 11:01 UTC, oliverklee requested changes
We also need to include the `Build` folder to be processed by PHP-CS-Fixer and PHP_CodeSniffer now.

2024-09-17 11:01 UTC, oliverklee commented on composer.json
> +		"ci:php:lint": "parallel-lint *.php Classes Configuration Tests",
As we now have our first PHP file in `Build`, we need to PHP-lint it as well.

2024-09-17 14:26 UTC, oliverklee requested changes
We still need to add  `Build` to the files that PHP-CS-Fixer and PHP_CodeSniffer check.

2024-09-30 07:48 UTC, oliverklee reviewed
We still need to add `Build/` to the list of directories that get stylechecked/fixed by PHP_CodeSniffer and PHP-CS-Fixer.

Also, could you please resolve the merge conflict?

2025-01-20 14:59 UTC, lukaszuznanski commented
Hi,

We've implemented a policy to close pull requests that have been inactive for over six months. If you're still interested in contributing and would like to continue working on this pull request, we're more than happy to keep it open.

Please take a moment to review your pull request and let us know if you'd like to proceed with it. If we don't receive a response within the next 30 days, we'll assume that you no longer wish to pursue it, and we'll proceed with closing the pull request.

Feel free to reach out if you have any questions or need further assistance.

2025-01-20 16:10 UTC, oliverklee approved these changes

2025-01-20 16:10 UTC, merged